module.exports =
  chainso: new RegExp('\b\B')
  counterparty: new RegExp('\b\B')
  dogeparty: new RegExp('\b\B')
  mastercoin: new RegExp('^[13][a-km-zA-HJ-NP-Z0-9]{26,33}$')
  ethereum: new RegExp('^(NXT)-[a-km-zA-HJ-NP-Z0-9]{1,4}-[a-km-zA-HJ-NP-Z0-9]{1,4}-[a-km-zA-HJ-NP-Z0-9]{1,4}-[a-km-zA-HJ-NP-Z0-9]{1,5}$')
  ripple: new RegExp('\b\B')
  nxt: new RegExp('\b\B')
  nxtassets: new RegExp('\b\B')
  nxtcurrencies: new RegExp('\b\B')
  coloredcoins: new RegExp('\b\B')
  nem: new RegExp('\b\B')
  cryptoid: new RegExp('\b\B')
  openassets: new RegExp('\b\B')
